name: barealek.dev
services:
  web:
    image: ghcr.io/barealek/ifpage:latest
    environment:
      - TERM=xterm-256color
    tty: true

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    env_file:
      - prod.env

    depends_on:
      - web

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
