services:
  nginx:
    build:
      context: .
    ports:
      - 9000:80
    volumes:
      - ./php/:/var/www/html:ro
      - ./logs/nginx:/var/log/nginx/
  php:
    image: php:fpm-alpine
    volumes:
      - ./php/:/var/www/html:ro
      - ./logs/php.log:/var/log/fpm-php.www.log
