name: alek.codes
services:
  web:
    image: ghcr.io/barealek/ifpage:latest
    environment:
      - TERM=xterm-256color
    tty: true

  cloudflare-tunnel:
    container_name: tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    env_file:
      - prod.env

    depends_on:
      - web
