name: alek.codes
services:
  web:
    image: ghcr.io/barealek/ifpage:latest

  cloudflare-tunnel:
    container_name: tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    env_file:
      - prod.env
    environment:
      - TERM=xterm-256color

    depends_on:
      - web
