name: barealek.dev
services:
  web:
    image: ghcr.io/barealek/ifpage:latest
    environment:
      - TERM=xterm-256color
    tty: true
    networks:
      - public

networks:
  public:
    external: true
